POST http://localhost:4000/resource/create/123 HTTP/1.1
Content-Type: application/json

{
    "inputNotes": "Inside double braces:{{`expression`}}.Can also be written inside a directive:ng-bind='expression'.AngularJS Expressions vs. JavaScript Expressions Like JavaScript expressions, AngularJS expressions can contain literals, operators, and variables. Unlike JavaScript expressions, AngularJS expressions can be written inside HTML. AngularJS expressions do not support conditionals, loops, and exceptions, while JavaScript expressions do.expressions support filters, while JavaScript expressions do not. Example {{ 5 + 5 }} or {{ firstName + ' ' + lastName }}"
}

###
POST http://localhost:4000/resource/chat/new-message/223 HTTP/1.1
Content-Type: application/json

{
    "messageText": "how to support your collegues?",
    "dateTime": 1684435969
}